export const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  UPDATE_CART: 'UPDATE_CART',
  GO_TO_CHECKOUT: 'GO_TO_CHECKOUT',
};
